### PR TITLE
Fixing autoescape bug and moving sample handlers to separate directory

### PR DESCRIPTION
**Pull request by carstein**
List of changes:
- XSS handler checks if proper jinja2 extension is loaded
- sample handlers moved to separate directory

### CODE REVIEW

**Comment by pames** [comment]
Out of curiosity, did you delete + re-add the handler files?  Or did you use git mv?

(git mv would preserve blame / revision history for the example handler file).

**Comment by carstein** [comment]
delete and re-add.
If you want to I can git mv them.

2015-11-23 20:02 GMT+01:00 Phil Ames notifications@github.com:

> Out of curiosity, did you delete + re-add the handler files? Or did you
> use git mv?
> 
> (git mv would preserve blame / revision history for the example handler
> file).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/gae-secure-scaffold-python/pull/11#issuecomment-159029172
> .

## 

Michal Melewski

**Comment by pames** [comment]
Yes, a git mv would be great since then it would also properly show the changes you made to the handler to fix the check for the autoescape extension.

**Comment by carstein** [comment]
in the morning then

2015-11-23 20:11 GMT+01:00 Phil Ames notifications@github.com:

> Yes, a git mv would be great since then it would also properly show the
> changes you made to the handler to fix the check for the autoescape
> extension.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/gae-secure-scaffold-python/pull/11#issuecomment-159031771
> .

## 

Michal Melewski

**Pull request merged**
